# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YeniCizimP/Arayuz/QtDesignerUI/ElemanSilKutusu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KatmanSil(object):
    def setupUi(self, KatmanSil):
        KatmanSil.setObjectName("KatmanSil")
        KatmanSil.resize(277, 263)
        KatmanSil.setSizeGripEnabled(False)
        KatmanSil.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(KatmanSil)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Sil = QtWidgets.QRadioButton(KatmanSil)
        self.Sil.setObjectName("Sil")
        self.verticalLayout.addWidget(self.Sil)
        self.Aktar = QtWidgets.QRadioButton(KatmanSil)
        self.Aktar.setObjectName("Aktar")
        self.verticalLayout.addWidget(self.Aktar)
        self.katmanListesi = QtWidgets.QListWidget(KatmanSil)
        self.katmanListesi.setObjectName("katmanListesi")
        self.verticalLayout.addWidget(self.katmanListesi)
        self.sonuc = QtWidgets.QDialogButtonBox(KatmanSil)
        self.sonuc.setOrientation(QtCore.Qt.Horizontal)
        self.sonuc.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.sonuc.setCenterButtons(False)
        self.sonuc.setObjectName("sonuc")
        self.verticalLayout.addWidget(self.sonuc)

        self.retranslateUi(KatmanSil)
        self.sonuc.accepted.connect(KatmanSil.accept)
        self.sonuc.rejected.connect(KatmanSil.reject)
        QtCore.QMetaObject.connectSlotsByName(KatmanSil)

    def retranslateUi(self, KatmanSil):
        _translate = QtCore.QCoreApplication.translate
        KatmanSil.setWindowTitle(_translate("KatmanSil", "Eleman Sil"))
        self.Sil.setText(_translate("KatmanSil", "Elemanları Sil"))
        self.Aktar.setText(_translate("KatmanSil", "Elemanları Katmana Aktar"))
