# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YeniCizimP/Arayuz/QtDesignerUI/KatmanKutusu1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KatmanDuzenleme(object):
    def setupUi(self, KatmanDuzenleme):
        KatmanDuzenleme.setObjectName("KatmanDuzenleme")
        KatmanDuzenleme.resize(550, 300)
        KatmanDuzenleme.setSizeGripEnabled(False)
        KatmanDuzenleme.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(KatmanDuzenleme)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.KatmanEkle = QtWidgets.QPushButton(KatmanDuzenleme)
        self.KatmanEkle.setObjectName("KatmanEkle")
        self.horizontalLayout_2.addWidget(self.KatmanEkle)
        self.katmanSil = QtWidgets.QPushButton(KatmanDuzenleme)
        self.katmanSil.setObjectName("katmanSil")
        self.horizontalLayout_2.addWidget(self.katmanSil)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.katmanListesi = QtWidgets.QTableWidget(KatmanDuzenleme)
        self.katmanListesi.setAutoScrollMargin(16)
        self.katmanListesi.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.katmanListesi.setAlternatingRowColors(False)
        self.katmanListesi.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.katmanListesi.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.katmanListesi.setTextElideMode(QtCore.Qt.ElideRight)
        self.katmanListesi.setShowGrid(True)
        self.katmanListesi.setGridStyle(QtCore.Qt.DashLine)
        self.katmanListesi.setWordWrap(True)
        self.katmanListesi.setCornerButtonEnabled(True)
        self.katmanListesi.setRowCount(0)
        self.katmanListesi.setColumnCount(7)
        self.katmanListesi.setObjectName("katmanListesi")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.katmanListesi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.katmanListesi.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.katmanListesi.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.katmanListesi.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.katmanListesi.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.katmanListesi.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.katmanListesi.setHorizontalHeaderItem(6, item)
        self.katmanListesi.horizontalHeader().setVisible(True)
        self.katmanListesi.horizontalHeader().setCascadingSectionResizes(False)
        self.katmanListesi.horizontalHeader().setHighlightSections(False)
        self.katmanListesi.horizontalHeader().setSortIndicatorShown(True)
        self.katmanListesi.horizontalHeader().setStretchLastSection(False)
        self.katmanListesi.verticalHeader().setVisible(True)
        self.katmanListesi.verticalHeader().setCascadingSectionResizes(False)
        self.katmanListesi.verticalHeader().setDefaultSectionSize(20)
        self.katmanListesi.verticalHeader().setHighlightSections(False)
        self.katmanListesi.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout.addWidget(self.katmanListesi)

        self.retranslateUi(KatmanDuzenleme)
        QtCore.QMetaObject.connectSlotsByName(KatmanDuzenleme)

    def retranslateUi(self, KatmanDuzenleme):
        _translate = QtCore.QCoreApplication.translate
        KatmanDuzenleme.setWindowTitle(_translate("KatmanDuzenleme", "Katman Düzenleme"))
        self.KatmanEkle.setText(_translate("KatmanDuzenleme", "Ekle"))
        self.katmanSil.setText(_translate("KatmanDuzenleme", "Sil"))
        self.katmanListesi.setSortingEnabled(True)
        item = self.katmanListesi.horizontalHeaderItem(0)
        item.setText(_translate("KatmanDuzenleme", "Katman Adı"))
        item = self.katmanListesi.horizontalHeaderItem(1)
        item.setText(_translate("KatmanDuzenleme", "Kilit"))
        item = self.katmanListesi.horizontalHeaderItem(2)
        item.setText(_translate("KatmanDuzenleme", "Görünüm"))
        item = self.katmanListesi.horizontalHeaderItem(3)
        item.setText(_translate("KatmanDuzenleme", "Kalınlık"))
        item = self.katmanListesi.horizontalHeaderItem(4)
        item.setText(_translate("KatmanDuzenleme", "Renk"))
        item = self.katmanListesi.horizontalHeaderItem(5)
        item.setText(_translate("KatmanDuzenleme", "Tip"))
        item = self.katmanListesi.horizontalHeaderItem(6)
        item.setText(_translate("KatmanDuzenleme", "Eleman Sayısı"))
